### ISSUE TITLE
Docker container node doesn't see the source node's IP, only sees Docker Bridge IP

### ISSUE THREAD

**Issue by convexshiba** [almeidapaulopt/tsdproxy#119]
**Before file a bug**
verify if you case is already known in https://almeidapaulopt.github.io/tsdproxy/docs/troubleshooting/
Yes

**Describe the bug**
When visiting a node (Qbittorrent torrent) through tsdproxy, Qbit node only sees a connection through `::ffff:172.17.0.1`, instead of the actual IP v4 or v6 of the initiating node.

`WebAPI login success. IP: ::ffff:172.17.0.1`

**Expected behavior**
It receives the actual tailscale IPv4 or IPv6 of the initiating node.

**Send config**
Send the config tsdproxy.yaml file.
https://privatebin.net/?ea15d970b885b52f#hYmB7HvEUM76faMy1vQcnVRKMMaFZtQsaz7naREetmH

**Logs**
Always send logs

https://privatebin.net/?895b8d960d3bb803#CSq2z48VmGqkAQvnCyTJGLjqfyK84i2fN3q7sngUaLCP

**Additional context**

Hope to know if this is expected behavior, and if there's ways to configure Tailscale to achieve this. Thanks.

**Comment by almeidapaulopt** [comment]
TSDProxy search for the internal docker networks to connect to target (qbittorrent).
If you don't want that add   tsdproxy.autodetect: "false" to your container..

**Comment by convexshiba** [comment]
Thanks for responding.

I added `tsdproxy.autodetect = false` to the qbittorrent container. Restarted TSDProxy.

But the behavior is still the same that qbittorrent log shows connection coming from 172.17.0.1
"WebAPI login success. IP: ::FFF: 172.17.0.1"

**Comment by almeidapaulopt** [comment]
That should be the gateway of tsdproxy docker network. To achieve what you want you have to install as a standalone and not in a container. That's not a tsdproxy issue is a network definition
