### ISSUE TITLE
Configuration File Not Generated on Application Start Starting with Version 1.2.0

### ISSUE THREAD

**Issue by jasonc** [almeidapaulopt/tsdproxy#121]
**Before file a bug**
I reviewed the troubleshooting guide but did not find this issue listed.

**Describe the bug**
Starting from version 1.2.0, the application fails to create the default tsdproxy.yaml configuration file on startup if it does not already exist. This issue does not occur in version 1.1.2, where the configuration file is successfully generated.

**Error Message**
Initializing server
Version 1.2.1
loading configuration from: /config/tsdproxy.yaml
error: open /config/tsdproxy.yaml: no such file or directory

**Expected behavior**
If the configuration file (tsdproxy.yaml) does not exist, the application should automatically generate a default configuration file (as in version 1.1.2).

**Send config**
docker run almeidapaulopt/tsdproxy:latest

**Logs**
Initializing server
Version 1.2.1
loading configuration from: /config/tsdproxy.yaml
error: open /config/tsdproxy.yaml: no such file or directory

**Additional context**

I think commit 212b27537e860387d407d20be43d8c9bad9316ab of the Makefile could be the cause of this issue, but I can't get version 1.2.0+ to build and confirm the change.

    -               wgo run -file=.go -file=.yaml -file=.env -file=.json -file=.toml ${MAIN_PACKAGE_PATH} -config ./dev/tsdproxy.yaml
    +               wgo run -file=.go -file=.env -file=.json ${MAIN_PACKAGE_PATH} -config ./dev/tsdproxy-local.yaml

**Comment by appils** [comment]
yes, I have the same problem
hope this problem will be resolved soon

**Comment by cblinq** [comment]
Same problem.

**Comment by almeidapaulopt** [comment]
Should be ok with v1.3.0.

**Comment by jasonc** [comment]
You fixed it, @almeidapaulopt! Thank you!
