### ISSUE TITLE
`TSDPROXY_AUTHKEY` Environment Variable Does Not Override Key in tsdproxy.yaml

### ISSUE THREAD

**Issue by jasonc** [almeidapaulopt/tsdproxy#129]
**Describe the bug**
When setting the `TSDPROXY_AUTHKEY` environment variable, it does not override the key stored in the `tsdproxy.yaml` configuration file as expected. Instead, the key in the YAML file takes precedence. This behavior prevents dynamic key updates via environment variables, which is useful in containerized or automated deployments.

**Expected behavior**
The `TSDPROXY_AUTHKEY` environment variable should override the key stored in the `tsdproxy.yaml` file.

**Comment by almeidapaulopt** [comment]
Env variables are deprecated since 0.6.0 because of multi Tailscale accounts feature.
See https://almeidapaulopt.github.io/tsdproxy/docs/serverconfig/
