### ISSUE TITLE
Port options

### ISSUE THREAD

**Issue by flexyneat** [almeidapaulopt/tsdproxy#16]
Hi,

This a nice project, I set it up yesterday using docker compose, however I already have port 80 and 8080 in-use on my docker host, so I tried to expose it as "85:8080" but that didn't seem to work.

What other options do we have for using the non-standard ports with this container?

**Comment by shanelord01** [comment]
You shouldn't be exposing ports in the TSDProxy Docker Container.

You do that in the config for the docker application you want to expose using labels.

Follow the instructions to get TSDProxy running here: 
https://almeidapaulopt.github.io/tsdproxy/docs/getting-started/

Then add the labels you need to your docker container config for the application you want to expose as per here:
https://almeidapaulopt.github.io/tsdproxy/docs/services/
