### ISSUE TITLE
HTTP to HTTPS redirection not working on phone browsers

### ISSUE THREAD

**Issue by eduardmerino** [almeidapaulopt/tsdproxy#28]
## Description
I'm experiencing an issue where the HTTP to HTTPS redirection is not functioning on mobile browsers. This works fine on desktop browsers, but it fails to redirect correctly when accessing any of my sites using my iPhone.

## Steps to Reproduce
1. Open a phone browser.
2. Navigate to `http://yourdomain.funnyname.ts.net`.
3. The page does not redirect to `https://yourdomain.funnyname.ts.net` as expected and it shows ERR_CONNECTION_FAILED.
4. If I write https:// manually in front of the address it works.

## Additional Information
- **Browsers tested**: Safari (iOS), Chrome (iOS)

Any insights or assistance with this would be appreciated!

**Comment by almeidapaulopt** [comment]
fixed with https://github.com/almeidapaulopt/tsdproxy/commit/06d6d7c1740d23ecbcdc5af99ec275710255c698
