### ISSUE TITLE
"panic: no safe place found to store log state" when running under Podman

### ISSUE THREAD

**Issue by jphays** [almeidapaulopt/tsdproxy#33]
I'm trying to set up tsdproxy running on Podman. I got the container running successfully, but as soon as I added the `tsdproxy.*` labels to an existing container, the tsdproxy container died. 

The log output at the time of death is **"panic: no safe place found to store log state"**. This seems to come from [logpolicy.go](https://github.com/tailscale/tailscale/blob/cf41cec5a8da13809fab472e221aecd099009b6f/logpolicy/logpolicy.go#L267) in the tailscale client, when it falls back to trying to create a temp directory after not finding a state directory. I'd assume this would be something under /data by default, but maybe some environment needs to be set?

I'm running this on Fedora Server 41 and have SELinux enabled, but don't see any access control errors in SELinux logs (I did have to fix access control to the socket device to get the container to start). I don't have Docker installed on this device and haven't personally tried running the image under Docker yet.

Here's the full log output:

```
tailscale-proxy  | Initializing server
tailscale-proxy  | 9:56PM INF Log Settings Log level=info
tailscale-proxy  | 9:56PM INF Starting server Version=
tailscale-proxy  | 9:56PM INF Setting up proxy for existing containers
tailscale-proxy  | Version
tailscale-proxy  | Setting up logger
tailscale-proxy  | 9:56PM INF setting up proxy for container containerID=7a9200a41402e1f0a51ead6d63f2dababda2477bfb06d8b6e982ed4dad92eb21
tailscale-proxy  | 9:56PM INF Initializing WebServer
tailscale-proxy  | 9:56PM INF Health check set to ready
tailscale-proxy  | 9:56PM INF [v1] using fake (no-op) tun device
[previous line repeated 25 times]
tailscale-proxy  | 9:56PM INF tsnet running state path /data/homepage/tailscaled.state
tailscale-proxy  | panic: no safe place found to store log state
tailscale-proxy  |
tailscale-proxy  | goroutine 36 [running]:
tailscale-proxy  | tailscale.com/logpolicy.LogsDir(0xc0004914f0)
tailscale-proxy  |      /home/runner/go/pkg/mod/tailscale.com@v1.76.6/logpolicy/logpolicy.go:264 +0x49a
tailscale-proxy  | tailscale.com/ipn/ipnlocal.NewLocalBackend(0xc0004914f0, {0x9d, 0x3, 0x65, 0x51, 0x10, 0xdc, 0x88, 0x8c, 0x34, ...}, ...)
tailscale-proxy  |      /home/runner/go/pkg/mod/tailscale.com@v1.76.6/ipn/ipnlocal/local.go:492 +0x93d
tailscale-proxy  | tailscale.com/tsnet.(*Server).start(0xc0004e0b60)
tailscale-proxy  |      /home/runner/go/pkg/mod/tailscale.com@v1.76.6/tsnet/tsnet.go:599 +0xd15
tailscale-proxy  | tailscale.com/tsnet.(*Server).doInit(0xc0004e0b60)
tailscale-proxy  |      /home/runner/go/pkg/mod/tailscale.com@v1.76.6/tsnet/tsnet.go:409 +0x78
tailscale-proxy  | sync.(*Once).doSlow(0x1a82e80?, 0xf2f6c0?)
tailscale-proxy  |      /opt/hostedtoolcache/go/1.23.3/x64/src/sync/once.go:76 +0xb4
tailscale-proxy  | sync.(*Once).Do(...)
tailscale-proxy  |      /opt/hostedtoolcache/go/1.23.3/x64/src/sync/once.go:67
tailscale-proxy  | tailscale.com/tsnet.(*Server).Start(0xc0004e0b60)
tailscale-proxy  |      /home/runner/go/pkg/mod/tailscale.com@v1.76.6/tsnet/tsnet.go:289 +0x6f
tailscale-proxy  | tailscale.com/tsnet.(*Server).LocalClient(...)
tailscale-proxy  |      /home/runner/go/pkg/mod/tailscale.com@v1.76.6/tsnet/tsnet.go:191
tailscale-proxy  | github.com/almeidapaulopt/tsdproxy/internal/tailscale.NewTsNetServer({0xc0004fc9b8, 0x8}, 0xc0003540a0, 0xc000349500, 0xc0004821c0)
tailscale-proxy  |      /home/runner/work/tsdproxy/tsdproxy/internal/tailscale/tailscale.go:44 +0x35f
tailscale-proxy  | github.com/almeidapaulopt/tsdproxy/internal/proxymanager.(*ProxyManager).SetupProxy(0xc00033d590, {0x132a220, 0x1aa8fe0}, {0xc0002d94c0, 0x40})
tailscale-proxy  |      /home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxymanager.go:151 +0x506
tailscale-proxy  | created by github.com/almeidapaulopt/tsdproxy/internal/proxymanager.(*ProxyManager).SetupExistingContainers in goroutine 1
tailscale-proxy  |      /home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxymanager.go:92 +0x24a
tailscale-proxy exited with code 0 
```

**Comment by jphays** [comment]
I managed to get beyond this by setting the environment variable `STATE_DIRECTORY=/data` on the tsdproxy container. Not sure if that is the right value, why it would need to be set in this case, or what the right fix is.

Once I got beyond that, I ran into another issue with it not finding the port for the container, even when it's explicitly set by the label. Maybe something with the Podman API? I'm going to try setting up a regular individual tailscale image to expose another container and see how that works under this environment.

**Comment by jphays** [comment]
Thanks for taking a look @almeidapaulopt, but I'm still not sure what's different about my case that I needed to explicitly set the state directory. I assume it's some difference between docker and podman. It seems that under podman, you have to explicitly set `STATE_DIRECTORY` in the container config. It would be nice if that were either documented or not required.

**Comment by geeksville** [comment]
Hi @almeidapaulopt fyi (thanks for your cool tool btw) this issue still exists when using podman to run tsdproxy.
thank you @jphays for the workaround.

I don't know enough about docker/podman/go logging to know if defining STATE_DIRECTORY is a good 'real' fix' but  it worked for me and **might** be harmless for docker users.

```
services:
  tsdproxy:
    image: docker.io/almeidapaulopt/tsdproxy:2
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      # needed to fix https://github.com/almeidapaulopt/tsdproxy/issues/33#issuecomment-2471796745
      STATE_DIRECTORY: /data

    volumes:
      # kevinh: use the user podman socket 
      - /run/user/1001/podman/podman.sock:/from_host/docker.sock:Z
      - datadir:/data:Z
      - ./config:/config:Z

volumes:
  datadir:
```
