### ISSUE TITLE
More detail about docker networking

### ISSUE THREAD

**Issue by phipolis** [almeidapaulopt/tsdproxy#35]
I was reading through the documentation and then the source trying to understand how networking functions between tsdproxy and labelled containers. Based on `tsdproxy.container_port` referencing the container's internal port, is the connection injected inside of the container itself? Does this mean that tsdproxied containers can be on different user-defined bridge networks, and thus unable to talk to each other? And can they refrain from defining an external port on the docker host?

I hope this is all the case, and this tool facilitates running multiple containers accessible only through TS and its ACLs. Can this be stated more explicitly?

Cheers!

**Comment by almeidapaulopt** [comment]
tsdproxy use the docker exposed port (for now there's some PR's to use internal too). So, for now, it's doesn't matter what network you use.
