### ISSUE TITLE
Some Containers Work; Some Do Not

### ISSUE THREAD

**Issue by cliss** [almeidapaulopt/tsdproxy#39]
Hello,
I am trying to proxy eight containers across two different stacks.

In one of the stacks, a couple of the containers work great. Upon adding a third, however, I see this in the logs:

```
2024/11/14 00:32:18 http: panic serving 100.67.109.63:56688: runtime error: index out of range [-1]
goroutine 3980 [running]:
net/http.(*conn).serve.func1()
	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.33.0/internal/json/base.go:15
github.com/rs/zerolog.(*Event).Str(0x131f360?, {0x11401a7?, 0xc00051d101?}, {0x113f9f8?, 0x800?})
	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.33.0/event.go:256 +0x134
github.com/rs/zerolog.(*Logger).newEvent(0xc0003d87e0, 0x1, 0x0)
	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.33.0/log.go:495 +0x169
github.com/rs/zerolog.(*Logger).Info(0xe470a5?)
	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.33.0/log.go:356 +0x1a
github.com/almeidapaulopt/tsdproxy/internal/proxymanager.(*ProxyManager).SetupProxy.(*Logger).LoggerMiddleware.func3({0x1328390, 0xc0051cb0a0}, 0xc005f383c0)
	/home/runner/work/tsdproxy/tsdproxy/internal/core/log.go:96 +0x187
net/http.HandlerFunc.ServeHTTP(0x46b3f9?, {0x1328390?, 0xc0051cb0a0?}, 0xc000271b70?)
	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:2220 +0x29
net/http.serverHandler.ServeHTTP({0xc005542d50?}, {0x1328390?, 0xc0051cb0a0?}, 0x6?)
	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc0056bfa70, {0x132a258, 0xc0005136b0})
	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 2821
	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:3360 +0x485
```

And later:

`2024/11/14 00:32:34 http: TLS handshake error from 100.67.109.63:56689: remote error: tls: unknown certificate`

`.63` is my workstation, which is on macOS. I'm using Safari, though using Chrome doesn't matter.

This new container is configured analogously to the others; I haven't a clue why it's failing…?

**Comment by cliss** [comment]
An additional error:

`2024/11/14 01:01:58 http: TLS handshake error from 100.67.109.63:54953: Get "http://local-tailscaled.sock/localapi/v0/cert/{container}.{fun-name}.ts.net?type=pair&min_validity=0s": context deadline exceeded`

**Comment by almeidapaulopt** [comment]
Now that you ha this working, can you identify anything you could have done differently in this container?

**Comment by cliss** [comment]
I don't _think_ so? I'd happily believe this was user error, but I can't say that I know anything I've messed up. 🤪

**Comment by almeidapaulopt** [comment]
it would be interesting to understand why this appended. I'll close this

**Comment by poopledc** [comment]
This is happening to me, except I am trying to run only one instance of TSDProxy. Restarts do not seem to work. I can get one service to proxy, but then the rest won't. This started happening suddenly after a restart.
