### ISSUE TITLE
Some clarification about TSDPROXY_HOSTNAME ?

### ISSUE THREAD

**Issue by cattaildumpling** [almeidapaulopt/tsdproxy#42]
Hello @almeidapaulopt and others following this project! 

I would like to get some clarification about variable TSDPROXY_HOSTNAME when setting the TSDProxy Docker container up. 

The documentation says: `LAN IP address or name of docker host machine`

So here comes (maybe a stupid) question: What is the relevant interface that should be used here? eth0, tailscale0 or docker0? Or if I use hostname, should I used the one is assigned by Tailscale or hostname that my machine gives when I write "hostname" to the terminal outside of the Docker containers.  

Is the project going to work also with Taillock?

I would like to see also a little bit more description in the documentation about how the project works under the hood.

Thanks for giving your time for this great project!

**Comment by almeidapaulopt** [comment]
Next version TSDPROXY_HOSTNAME shouldn't be necessary. right now you should use your eth0 address.

about tailnet lock, what are you expecting to do?
