### ISSUE TITLE
Use for Channels DVR Server on Unraid

### ISSUE THREAD

**Issue by shanelord01** [almeidapaulopt/tsdproxy#5]
I've created a template for Unraid for TSDProxy [TSDProxy.txt](https://github.com/user-attachments/files/17640150/TSDProxy.txt) (rename from .txt to .xml and place in /boot/config/plugins/dockerMan/templates-user - then "Add Container" from the docker section of Unraid and select the TSDProxy template) and I have it running without errors. 

Note: I've tested TSDProxy with another app (immich) and it is working fine.

I've then added the required labels to the ChannelsDVR container - it is configured to use host networking (I just tried bridge as well - no luck) which is why I have setup port 8089 as the container port. The logs seem to show all is good, and the app is being presented in my Tailnet.

tsdproxy.enable: "true"
tsdproxy.container_port: 8089

I can also access ChannelsDVR over a web browser using the MagicDNS address, but the Channels iOS app fails to connect no matter what address I put in the address bar.

If I then setup the Channels native/built in Tailscale their IP address works fine in the app. Problem is their client is way out of date.

Any ideas what could be going wrong?

Thanks,
Shane.

**Comment by shanelord01** [comment]
Awesome product here BTW - working well for other items on Unraid.

**Comment by almeidapaulopt** [comment]
Hi

I don't know channels-dvr, but i've tryed with below docker compose and I was able to get the welcome page.


services:
  channels-dvr:
    image: fancybits/channels-dvr:latest
    container_name: channels-dvr
    network_mode: host
    ports:
      - "8089:8089"
    restart: on-failure:10
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./dvr/config:/channels-dvr
      - ./dvr/recordings:/shares/DVR
    labels:
      tsdproxy.enable: true
      tsdproxy.container_port: 8089
      tsdproxy.name: "channels-dvr"


Do you see any error in TSDProxy logs?

**Comment by shanelord01** [comment]
Hi - yes I can get the page also in a browser - just not in the iOS or Android app. I have Tailscale running on my device, choose "At Home" when prompted and put in the Tailscale address created via TSDProxy.

**Comment by noahkiss** [comment]
Assuming that's your real AuthKey in the TSDProxy.txt file, I suggest rotating it before someone else uses it.

**Comment by almeidapaulopt** [comment]
> Hi and thanks for looking - yes I can get the page also in a browser - just not in the iOS or Android app. I have Tailscale running on my device, choose "At Home" when prompted and put in the Tailscale address created via TSDProxy.
> 
> No errors in the TSDProxy logs.
send the logs on the moment you try to access with the app. it must be there something there.

**Comment by shanelord01** [comment]
> Assuming that's your real AuthKey in the TSDProxy.txt file, I suggest rotating it before someone else uses it.

Yes it was but I revoked it after I uploaded it. Thanks for keeping me safe!

> I found an old support thread for Channels which mentioned something about an auth error using bridge networking. I think it's probably just one of those apps where the dev team did some funky stuff to the app and so it doesn't behave the way most apps do when containerized.

Yeah I'm starting to think the same. I'll post on Channels forums and see if they have a suggestion.

**Comment by shanelord01** [comment]
OK - checking the Services presented by "channels-dvr" (created by TSDProxy) in Tailscale, it shows this:

![Screenshot 2024-11-07 at 10 31 08 AM](https://github.com/user-attachments/assets/9e8386de-43f0-4925-b0ef-980b072f3cca)

Where with the inbuilt Tailscale of Channels DVR directly, it shows:

![Screenshot 2024-11-07 at 10 34 24 AM](https://github.com/user-attachments/assets/a3a8a6ba-a89a-433a-a38a-71463c88dc0c)

I assume the Channels app is looking for port 8089 and not finding it. The only thing I see in the log is:

11:30PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

Thanks,
Shane.

**Comment by shanelord01** [comment]
OK found this post about an NGINX header to make it work through NGINX. https://community.getchannels.com/t/dvr-ios-with-nginx/8197

A few comments from it:

> Reverse proxy is not recommended as it breaks the authentication mechanism. Are you using your own authentication in nginx, or can anyone who knows the url access your DVR?

> One option is to have nginx add the header “X-DVR-ForceAuth: true” to the proxied request. Then you can remove the htpasswd (which the app has no idea how to deal with). You will be presented with an authorization form and will need to login using the authorization code from your dvr subscription account when accessing the web UI.
> 
> For the iOS app, you can click+hold the Authorize button and then copy the URL to change [https://xxx.channelsdvr.net:8089 2](https://xxx.channelsdvr.net:8089/) to [https://dvr.xxx.com 1](https://dvr.xxx.com/) and navigate to it. Note that if you do this, the app won’t understand that you’re connected remotely and so you’ll have to change the Home Streaming Quality setting back and forth.
> 
> Honestly it’s much easier just to enable port 8089, but that’s up to you.

Anything we can add to TSDProxy?

**Comment by shanelord01** [comment]
Yes it's setup correctly - I've tested it and can access the web interface of Channels via the MagicDNS address (ie 443 to 8089 over https). 

I think TSDproxy would need a port pass through mode to support apps like Channels. 

I already need to be on my Tailscale network to access my Channels server, ideally this would let me (optionally) directly show ports I need rather than proxy them.

**Comment by shanelord01** [comment]
@almeidapaulopt Is there an update that enables this to work with apps like ChannelsDVR?

**Comment by lucaguarro** [comment]
Don't mean to hijack this thread but @shanelord01 could you help me out and share your docker compose for tsdproxy and immich since you said you got it working?? I am able to use tsdproxy to run jellyfin and that works but can't get it working for immich.
