### ISSUE TITLE
Unable to use hocalhost or 127.0.0.1 as TSDPROXY_HOSTNAME

### ISSUE THREAD

**Issue by MrAvana** [almeidapaulopt/tsdproxy#6]
I'm trying to use localhost or 127.0.0.1 as the TSDPROXY hostname but it's not forwarding the connections. 

Thanks again for this great piece of software!

**Comment by almeidapaulopt** [comment]
> I'm trying to use localhost or 127.0.0.1 as the TSDPROXY hostname but it's not forwarding the connections.
> 
> Thanks again for this great piece of software!

localhost only work if you have tsdproxy in network_mode: host , it's better to use your host ip
