### ISSUE TITLE
Unable to get tsd proxy to add to my tailnet

### ISSUE THREAD

**Issue by newbieraf** [almeidapaulopt/tsdproxy#60]
Hi there

I cannot get tsd proxy to add my proxmox lxc to my tailnet - I must me missing something.  My environment

Proxmox LXC running Ubuntu
Installed tailscale inside LXC
Docker and docker compose installed
LXC is running Homarr via docker

The goal is to expose homarr to my tailnet

Things that I've done:

Created tsd proxy container per the instructions
Added the required labels to homarr compose file and recreated

Homarr and tsd are running but nothing is being added to my tailnet.

Im sure I'm missing something - can you help?

Thanks

**Comment by almeidapaulopt** [comment]
Can you send tsdproxy logs?

**Comment by almeidapaulopt** [comment]
it's there "you must enable HTTPS in the admin panel to proceed". go to tailscale admin panel and enable https

**Comment by newbieraf** [comment]
Yep all working now, just for other people who may read this.  Is it true to say that Https and magic DNS are required for TSD to work?

**Comment by almeidapaulopt** [comment]
> Https and magic DNS

I will add it to Documentation
