### ISSUE TITLE
how to serve services that run https

### ISSUE THREAD

**Issue by rburgst** [almeidapaulopt/tsdproxy#73]
I have a couple of containers that run offer themselves https via self signed certificates. Is there a way to have tsdp also proxy those which ignoring the cert? I have a setup running with nginx-proxy manager where this is supported.
It would be cool to have this also in tsdp so I dont need to reconfigure all my containers.
Thanks

**Comment by almeidapaulopt** [comment]
Just pushed ec45770e3da01dce28023591ca9a233884042c7c

You can now use a scheme label. 
Set scheme to https and it should work for you.

https://almeidapaulopt.github.io/tsdproxy/docs/services/#tsdproxyscheme
