### ISSUE TITLE
Allow tsdproxy connections without exposing container ports

### ISSUE THREAD

**Issue by the-root42** [almeidapaulopt/tsdproxy#95]
Is it possible to allow connections to containers without exposing any ports to the local network. For example, I'd like the ability to do the following:

```shell
app:
    image: containerimage:latest
    container_name: app
    ports:
      - 13378:80
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: tsname
      tsdproxy.ephemeral: "true"
      tsdproxy.container_port: 80
    volumes:
      - ./config:/config
    restart: unless-stopped
``` 

instead of 

```shell
app:
    image: containerimage:latest
    container_name: app
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: tsname
      tsdproxy.ephemeral: "true"
      tsdproxy.container_port: 80
    volumes:
      - ./config:/config
    restart: unless-stopped
```

**Comment by oneingan** [comment]
You don't need to expose ports. tsdproxy connects directly trough internal network between containers.

**Comment by the-root42** [comment]
Interesting, every time I remove the ports section from my compose file, I lose the ability to connect to the container through tailscale.  Is there a different configuration I should be using?

**Comment by oneingan** [comment]
maybe you can try with `tsdproxy.autodetect: "false"` label

**Comment by almeidapaulopt** [comment]
> You don't need to expose ports. tsdproxy connects directly trough internal network between containers.

you have to make sure the target is accessible by tsdproxy. Best way is they both in the same docker network.

**Comment by the-root42** [comment]
> you have to make sure the target is accessible by tsdproxy. Best way is they both in the same docker network.

This was this missing piece.  After creating a new docker network and adding both my tsdproxy container and my service container, everything worked.  Thanks!
