### ISSUE TITLE
scheme=https failed to verify certificate

### ISSUE THREAD

**Issue by vigge93** [almeidapaulopt/tsdproxy#96]
I tried running portainer with TSDProxy using scheme=https, and got the following error message:
```
2024/12/11 21:12:50 http: proxy error: tls: failed to verify certificate: x509: certificate is valid for 0.0.0.0, not 172.17.0.1
9:12PM ERR error host=portainer.FUNNY-NAME.ts.net method=GET module=proxymanager proxyname=portainer status=502 url=/
```
The two labels I have on the container are:
``` 
tsdproxy.enable: true
tsdproxy.scheme: https
```
Any assistance would be appreciated.

**Comment by oneingan** [comment]
you need to enable HTTPS Certificates in your Tailscale controlplane: https://tailscale.com/kb/1153/enabling-https

**Comment by almeidapaulopt** [comment]
> you need to enable HTTPS Certificates in your Tailscale controlplane: https://tailscale.com/kb/1153/enabling-https

its not that. its the target already has tls with self signed certificates

**Comment by almeidapaulopt** [comment]
set   tsdproxy.tlsvalidate: "false"

https://almeidapaulopt.github.io/tsdproxy/docs/docker/#tsdproxytlsvalidate

**Comment by vigge93** [comment]
That worked. Thank you!
